server.port=${PORT:8080}
#spring.datasource.url=${PG_JDBC_PRODUCTION_URL:jdbc:postgresql://localhost:5432/farmsetu}
#spring.datasource.username=${PGUSER:roshan}
#spring.datasource.password=${PG_PASSWORD_PRODUCTION:roshan1234}
 spring.datasource.url=jdbc:postgresql://localhost:5432/farmsetu
 spring.datasource.username=postgres
 spring.datasource.password=roshan1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
farmsetu.jwt.secret=${JWT_SECRET:secret}
farmsetu.jwt.access-expiration-ms=${JWT_EXPIRE:604800000}
farmsetu.jwt.refresh-expiration-ms=${JWT_REFRESH:2592000000}

# Brevo Email Configurations
brevo.api-key=${BREVO_API_KEY:}
brevo.sender.email=${BREVO_SENDER_EMAIL:no-reply@farmsetu.com}
brevo.sender.name=${BREVO_SENDER_NAME:FarmSetu}

spring.jackson.mapper.accept-case-insensitive-enums=true

# File Upload Configurations
spring.servlet.multipart.max-file-size=${FILE_UPLOAD_SIZE:10MB}
spring.servlet.multipart.max-request-size=${FILE_UPLOAD_SIZE:10MB}

# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.upload-preset=${CLOUDINARY_UPLOAD_PRESET:}
# Unified AI Configurations (gemini or openai)
ai.provider=${AI_PROVIDER:openai}

# For Gemini API (Google AI Studio)
gemini.api.key=${GEMINI_API_KEY:key-here}
gemini.model=${GEMINI_MODEL:gemini-3.5-flash}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}

# For OpenAI-compatible APIs (ChatGPT, DeepSeek, Groq, OpenRouter, Local Ollama)
openai.api.key=${GROQ_API_KEY:api key}
openai.model=${GROQ_MODEL:llama-3.3-70b-versatile}
openai.base-url=${GROQ_BASE_URL:https://api.groq.com/openai}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO_MODE:none}
# HikariCP optimizations for remote latency
# Limit idle connections to 1 (instead of 10) so it doesn't open 10 SSL handshakes at startup
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
# Prevent application startup from hanging if network briefly drops
spring.datasource.hikari.initialization-fail-timeout=-1
